# This workflow will test a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ test-build ]
  pull_request:
    branches: [ test-build ]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out the respository
      uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}

    - name: Test with Maven
      run: mvn -B test --file ./*/pom.xml
